metric: COCO
num_classes: 6

TrainDataset:
  !COCODataSet
    image_dir: D:\test\PaddleDetection-release-2.4\cocome\train
    anno_path: D:\test\PaddleDetection-release-2.4\cocome\annotations\instance_train.json
    dataset_dir: D:\test\PaddleDetection-release-2.4\cocome
    data_fields: [ 'image', 'gt_bbox', 'gt_class', 'is_crowd' ]

EvalDataset:
  !COCODataSet
    image_dir: D:\test\PaddleDetection-release-2.4\cocome\train
    anno_path: D:\test\PaddleDetection-release-2.4\cocome\annotations\instance_val.json
    dataset_dir: D:\test\PaddleDetection-release-2.4\cocome

TestDataset:
  !ImageFolder
    anno_path: D:\test\PaddleDetection-release-2.4\cocome\annotations\instance_test.json # also support txt (like VOC's label_list.txt)
    dataset_dir: D:\test\PaddleDetection-release-2.4\cocome # if set, anno_path will be 'dataset_dir/anno_path'
