metric: COCO
num_classes: 6

TrainDataset:
  !COCODataSet
    image_dir: /home/mayanmei/ocr_project/PaddleDetection/cocome/train
    anno_path: /home/mayanmei/ocr_project/PaddleDetection/cocome/annotations/instance_train.json
    dataset_dir: /home/mayanmei/ocr_project/PaddleDetection/cocome/
    data_fields: [ 'image', 'gt_bbox', 'gt_class', 'is_crowd' ]

EvalDataset:
  !COCODataSet
    image_dir: /home/mayanmei/ocr_project/PaddleDetection/cocome/train
    anno_path: /home/mayanmei/ocr_project/PaddleDetection/cocome/annotations/instance_val.json
    dataset_dir: /home/mayanmei/ocr_project/PaddleDetection/cocome/

TestDataset:
  !ImageFolder
    anno_path: /home/mayanmei/ocr_project/PaddleDetection/cocome/annotations/instance_test.json # also support txt (like VOC's label_list.txt)
    dataset_dir: /home/mayanmei/ocr_project/PaddleDetection/cocome/ # if set, anno_path will be 'dataset_dir/anno_path'
